create table SBS_STG_CLIENTE
(
COD_CLIENTE_SBS VARCHAR,
FEC_REPORTE VARCHAR,
TIP_DOCUMENTO_TRIB VARCHAR,
COD_RUC VARCHAR,
TIP_DOCUMENTO_IDENT VARCHAR,
COD_DNI VARCHAR,
TIP_PERSONA VARCHAR,
TIP_EMPRESA VARCHAR,
CNT_EMPRESA VARCHAR,
POR_SALDO_DEUDA_TIP0  VARCHAR,
POR_SALDO_DEUDA_TIP1 VARCHAR,
POR_SALDO_DEUDA_TIP2 VARCHAR,
POR_SALDO_DEUDA_TIP3 VARCHAR,
POR_SALDO_DEUDA_TIP4 VARCHAR,
NOM_RAZON_SOCIAL VARCHAR,
NOM_APE_MATERNO VARCHAR,
NOM_APE_CASADA VARCHAR,
NOM_PRIMER_NOMBRE VARCHAR,
NOM_SEGUNDO_NOMBRE VARCHAR
);


create table SBS_STG_SALDO
(
COD_CLIENTE_SBS VARCHAR,
COD_ENTIDAD VARCHAR,
TIP_CREDITO VARCHAR,
COD_CUENTA VARCHAR,
NUM_CONDICION_DIAS VARCHAR,
MTO_SALDO VARCHAR,
TIP_CLASIFICACION VARCHAR,
FEC_REPORTE VARCHAR
);

CREATE TABLE SBS_ODS_PRODUCTO
( 
	COD_PRODUCTO       integer  NOT NULL ,
	DES_PRODUCTO       varchar  NULL ,
	COD_GRP_PRODUCTO   varchar  NULL 
)
go

CREATE TABLE SBS_ODS_REL_PRODUCTO
( 
	COD_CUENTA         integer  NOT NULL ,
	COD_PRODUCTO       integer  NOT NULL ,
	TIP_CREDITO        varchar(20)  NOT NULL ,
	COD_PERIODO        integer  NOT NULL 
)
go

CREATE TABLE SBS_DIM_CLIENTE
( 
	COD_CLIENTE_SBS    NUMBER  NOT NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_CLIENTE_PROP   NUMBER  NULL ,
	TIP_DOCUMENTO_JUR  VARCHAR  NULL ,
	COD_DOCUMENTO_JUR  VARCHAR  NULL ,
	TIP_DOCUMENTO_NAT  VARCHAR  NULL ,
	COD_DOCUMENTO_NAT  VARCHAR  NULL ,
	TIP_PERSONA        VARCHAR  NULL ,
	COD_PERIODO_BANCARIZACION VARCHAR  NULL ,
	COD_PRODUCTO_BANCARIZACION NUMBER  NULL ,
	COD_ENTIDAD_BANCARIZACION NUMBER  NULL ,
	TIP_SITUACION_BANCARIZACION VARCHAR  NULL ,
	COD_PERIODO_COSECHA_PROP VARCHAR  NULL ,
	COD_PRODUCTO_COSECHA_PROP NUMBER  NULL ,
	COD_PERIODO_ULT_PROP VARCHAR  NULL ,
	TIP_SITUACION_PROP VARCHAR  NULL ,
	NOM_PRIMER_NOMBRE  VARCHAR  NULL ,
	NOM_SEGUNDO_NOMBRE VARCHAR  NULL ,
	NOM_APE_PATERNO    VARCHAR  NULL ,
	NOM_APE_MATERNO    VARCHAR  NULL ,
	CNT_CPPDDP_3M      NUMBER  NULL ,
	CNT_DDP_24M        NUMBER  NULL ,
	CNT_NORMAL_12M     NUMBER  NULL ,
	FLG_GARANTIA       VARCHAR  NULL ,
	FLG_SALDO_PMM_24M  NUMBER  NULL ,
	MTO_SALDO_PP_MAX_24M NUMBER  NULL ,
	MTO_LINEATC_MAX_24M NUMBER  NULL ,
	MTO_SALDO_PMM_MAX_24M NUMBER  NULL ,
	COD_PERIODO_SALDO_PP_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_LINEATC_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_PMM_MAX_24M VARCHAR  NULL ,
	COD_UBIGEO         VARCHAR(20)  NOT NULL ,
	COD_SEGMENTO_PROP  VARCHAR  NULL ,
	TIP_MUNDO_CONSUMO  VARCHAR  NULL ,
	MTO_INGRESO_CLI    NUMBER  NULL ,
	MTO_CUOTA_MES      NUMBER  NULL ,
	COD_PERIODO_ULT    char(18)  NULL ,
	TIP_CLASIFICACION_ULTMES char(18)  NULL ,
	TIP_MUNDO_PMM      char(18)  NULL ,
	TIP_MUNDO_HIP      char(18)  NULL,
	PRIMARY KEY (COD_CLIENTE_SBS,COD_UBIGEO)
)
;


CREATE TABLE SBS_DIM_CUENTA
( 
	COD_CUENTA         NUMBER  NOT NULL ,
	DES_CUENTA         VARCHAR  NULL ,
	COD_NIVEL1         NUMBER  NULL ,
	DES_NIVEL1         VARCHAR(20)  NULL ,
	COD_NIVEL2         NUMBER  NULL ,
	DES_NIVEL2         char(18)  NULL ,
	COD_NIVEL3         NUMBER  NULL ,
	DES_NIVEL3         char(18)  NULL ,
	COD_NIVEL4         NUMBER  NULL ,
	DES_NIVEL4         char(18)  NULL ,
	COD_NIVEL5         NUMBER  NULL ,
	DES_NIVEL5         char(18)  NULL,
	PRIMARY KEY (COD_CUENTA)
)
;

CREATE TABLE SBS_DIM_ENTIDAD
( 
	COD_ENTIDAD        VARCHAR(20)  NOT NULL ,
	DES_ENTIDAD        VARCHAR  NULL ,
	DES_ALIAS          VARCHAR  NULL ,
	TIP_ENTIDAD        VARCHAR  NULL ,
	TIP_ENTIDAD_PROP   VARCHAR  NULL ,
	PRIMARY KEY (COD_ENTIDAD)
)
;

CREATE TABLE SBS_DIM_PRODUCTO
( 
	COD_PRODUCTO       NUMBER  NOT NULL ,
	DES_PRODUCTO       VARCHAR  NULL ,
	COD_GRP_PRODUCTO   VARCHAR  NULL ,
	PRIMARY KEY (COD_PRODUCTO)
)
;

CREATE TABLE SBS_DIM_UBIGEO
( 
	COD_UBIGEO         VARCHAR(20)  NOT NULL ,
	DES_PROVINCIA      VARCHAR  NULL ,
	DES_DEPARTAMENTO   VARCHAR  NULL ,
	DES_ZONA           VARCHAR  NULL ,
	DES_REGION_PROP    VARCHAR  NULL ,
	DES_DISTRITO       char(18)  NULL ,
	FLG_CIUDAD_PROP    char(18)  NULL ,
	DES_GRP_DISTRITO_PROP char(18)  NULL ,
	FLG_CAPITAL        char(18)  NULL ,
	PRIMARY KEY (COD_UBIGEO)
)
;


CREATE TABLE SBS_FACT_CLIENTE
( 
	COD_PERIODO        NUMBER  NOT NULL ,
	COD_CLIENTE_SBS    NUMBER  NOT NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR  NULL ,
	TIP_PERSONA        VARCHAR  NULL ,
	POR_DEUDA_TIPO0    NUMBER  NULL ,
	POR_DEUDA_TIPO1    NUMBER  NULL ,
	POR_DEUDA_TIPO2    NUMBER  NULL ,
	POR_DEUDA_TIPO3    NUMBER  NULL ,
	POR_DEUDA_TIPO4    NUMBER  NULL ,
	TIP_CLASIFICACION  NUMBER  NULL ,
	TIP_SIT_BANCARIZACION VARCHAR  NULL ,
	TIP_ENTIDAD_PROP_MAX VARCHAR  NULL ,
	CNT_ENTIDAD        NUMBER  NULL ,
	CNT_ENTIDAD_SALDOTC NUMBER  NULL ,
	CNT_ENTIDAD_LINEATC NUMBER  NULL ,
	CNT_ENTIDAD_PP     NUMBER  NULL ,
	CNT_ENTIDAD_PMM    NUMBER  NULL ,
	CNT_ENTIDAD_LINEA_PMM NUMBER  NULL ,
	CNT_ENTIDAD_HIP    NUMBER  NULL ,
	MTO_SALDO          NUMBER  NULL ,
	MTO_SALDO_INDIRECTO NUMBER  NULL ,
	MTO_SALDO_CONSUMO  NUMBER  NULL ,
	MTO_SALDO_CONSUMO_TC NUMBER  NULL ,
	MTO_SALDO_CONSUMO_LD NUMBER  NULL ,
	MTO_SALDO_CONSUMO_VEH NUMBER  NULL ,
	MTO_SALDO_CONSUMO_TC_DEF NUMBER  NULL ,
	MTO_SALDO_LINEATC  NUMBER  NULL ,
	MTO_SALDO_MED      NUMBER  NULL ,
	MTO_SALDO_PEQ      NUMBER  NULL ,
	MTO_SALDO_MICRO    NUMBER  NULL ,
	MTO_SALDO_LINEA_PMM NUMBER  NULL ,
	MTO_SALDO_HIP      NUMBER  NULL ,
	MTO_SALDO_HIP_MIV  NUMBER  NULL ,
	MTO_SALDO_EMP      NUMBER  NULL ,
	MTO_SALDO_LINEA_EMP NUMBER  NULL ,
	MTO_SALDO_REFINANCIADO NUMBER  NULL ,
	MTO_SALDO_CASTIGO  NUMBER  NULL ,
	MTO_SALDO_JUDICIAL NUMBER  NULL ,
	MTO_SALDO_CONSUMO_PROP NUMBER  NULL ,
	MTO_SALDO_CONSUMO_TC_PROP NUMBER  NULL ,
	MTO_SALDO_CONSUMO_LD_PROP NUMBER  NULL ,
	MTO_SALDO_PMM_PROP NUMBER  NULL ,
	MTO_SALDO_LINEA_PMM_PROP NUMBER  NULL ,
	MTO_SALDO_LINA_TC_PROP NUMBER  NULL ,
	MTO_SALDO_REFINANCIADO_PROP NUMBER  NULL ,
	MTO_SALDO_CASTIGO_PROP NUMBER  NULL ,
	MTO_SALDO_JUDICIAL_PROP NUMBER  NULL ,
	COD_ENTIDAD_PRINC  NUMBER  NULL ,
	COD_ENTIDAD_PRINC_LINEA_TC NUMBER  NULL ,
	COD_ENTIDAD_PRINC_SALDO_TC NUMBER  NULL ,
	COD_ENTIDAD_PRINC_PP NUMBER  NULL ,
	COD_ENTIDAD_PRINC_PMM NUMBER  NULL ,
	COD_ENTIDAD_PRINC_LINEA_PMM NUMBER  NULL ,
	COD_ENTIDAD_PRINC_HIP NUMBER  NULL ,
	COD_ENTIDAD_PRINC_TC_DEF NUMBER  NULL ,
	MTO_CUOTA_MES      NUMBER  NULL ,
	MTO_INGRESO        NUMBER  NULL ,
	COD_SEGMENTO_PROP  NUMBER  NULL ,
	TIP_MUNDO_PMM      VARCHAR  NULL ,
	COD_DOCUMENTO_PRIN char(18)  NULL ,
	MTO_SALDO_CONSUMO_VEH_PROP NUMBER  NULL ,
	MTO_SALDO_CONSUMO_TC_DEF_PROP NUMBER  NULL ,
	TIP_MUNDO_CONSUMO  char(18)  NULL ,
	TIP_MUNDO_HIP      char(18)  NULL ,
	TIP_MUNDO_EMP      char(18)  NULL ,
	COD_UBIGEO         VARCHAR(20)  NOT NULL ,
	PRIMARY KEY (COD_PERIODO ,COD_CLIENTE_SBS ,COD_UBIGEO )
)
;


CREATE TABLE SBS_FACT_CLIENTE_ENTIDAD
( 
	COD_PERIODO        NUMBER  NOT NULL ,
	COD_CLIENTE_SBS    NUMBER  NOT NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_ENTIDAD        VARCHAR(20)  NOT NULL ,
	TIP_CLASIFICACION  NUMBER  NULL ,
	COD_PERIODO_COSECHA VARCHAR  NULL ,
	COD_PRODUCTO_COSECHA NUMBER  NULL ,
	MTO_SALDO          NUMBER  NULL ,
	MTO_SALDO_INDIRECTO NUMBER  NULL ,
	MTO_SALDO_CONSUMO  NUMBER  NULL ,
	MTO_SALDO_CONSUMO_TC NUMBER  NULL ,
	MTO_SALDO_CONSUMO_LD NUMBER  NULL ,
	MTO_SALDO_CONSUMO_VEH NUMBER  NULL ,
	MTO_SALDO_CONSUMO_TC_DEF NUMBER  NULL ,
	MTO_SALDO_LINEATC  NUMBER  NULL ,
	MTO_SALDO_MICRO    NUMBER  NULL ,
	MTO_SALDO_PEQ      NUMBER  NULL ,
	MTO_SALDO_MED      NUMBER  NULL ,
	MTO_SALDO_LINEA_PMM NUMBER  NULL ,
	MTO_SALDO_HIP      NUMBER  NULL ,
	MTO_SALDO_HIP_MIV  NUMBER  NULL ,
	MTO_SALDO_EMP      NUMBER  NULL ,
	MTO_SALDO_LINEAEMP NUMBER  NULL ,
	MTO_SALDO_REFINANCIADO NUMBER  NULL ,
	MTO_SALDO_CASTIGO  NUMBER  NULL ,
	MTO_SALDO_JUDICIAL NUMBER  NULL ,
	MTO_CUOTA_MES      NUMBER  NULL ,
	TIP_DOCUMENTO_PRINC VARCHAR(20)  NULL ,
	COD_UBIGEO         VARCHAR(20)  NOT NULL ,
	PRIMARY KEY (COD_PERIODO ,COD_CLIENTE_SBS ,COD_ENTIDAD ,COD_UBIGEO )
)
;

CREATE TABLE SBS_FACT_CLIENTE_ENTIDAD_PROD
( 
	COD_PERIODO        NUMBER  NOT NULL ,
	COD_CLIENTE_SBS    NUMBER  NOT NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_ENTIDAD        VARCHAR(20)  NOT NULL ,
	TIP_CLASIFICACION  NUMBER  NULL ,
	COD_PRODUCTO       NUMBER  NOT NULL ,
	MTO_SALDO          NUMBER  NULL ,
	COD_PERIODO_COSECHA VARCHAR  NULL ,
	TIP_ESTADO_PRODUCTO VARCHAR  NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR(20)  NULL ,
	COD_UBIGEO         VARCHAR(20)  NOT NULL ,
	PRIMARY KEY (COD_PERIODO ,COD_CLIENTE_SBS ,COD_ENTIDAD ,COD_PRODUCTO ,COD_UBIGEO )
)
;

CREATE TABLE SBS_FACT_SALDO
( 
	COD_CLIENTE_SBS    NUMBER  NOT NULL ,
	COD_ENTIDAD        VARCHAR(20)  NOT NULL ,
	TIP_CREDITO        VARCHAR  NOT NULL ,
	COD_CUENTA         NUMBER  NOT NULL ,
	NUM_CONDICION_DIAS NUMBER  NULL ,
	MTO_SALDO          NUMBER  NULL ,
	TIP_CLASIFICACION  NUMBER  NULL ,
	COD_PRODUCTO       NUMBER  NOT NULL ,
	COD_PERIODO        VARCHAR(20)  NOT NULL ,
	COD_UBIGEO         VARCHAR(20)  NOT NULL ,
	PRIMARY KEY (COD_PERIODO ,COD_CLIENTE_SBS ,COD_CUENTA ,TIP_CREDITO ,COD_ENTIDAD ,COD_PRODUCTO ,COD_UBIGEO )
)
;

