-- -------------------------------------------------------------------------------------------
-- 16. SBS_DIM_CLIENTE  -- CREATE TABLE SBS_DIM_CLIENTE03 AS SELECT * FROM SBS_DIM_CLIENTE
-- -------------------------------------------------------------------------------------------
-- DROP TABLE SBS_DIM_CLIENTE01
DROP TABLE  tp_flag_actualizar;

create table tp_flag_actualizar
(
  a_cod_cliente_sbs   NUMERIC(18,2) ,
  actualizar   varchar(1) -- 0 
);

-- CON ESTE QUERY IDENTIFICO A LOS QUE SE DEBEN ACTUALIZAR CON LA INFORMACION DEL PERIODO (0) 
-- Y LOS QUE NO APARECEN EN EL PERIODO ACTUAL (1) 

INSERT INTO  tp_flag_actualizar
SELECT
a_cod_cliente_sbs, actualizar
FROM (
        SELECT 
        a.COD_CLIENTE_SBS as a_cod_cliente_sbs,
        a.cod_periodo_ult as a_cod_periodo_ult,
        b.cod_cliente_sbs,
        case when b.cod_cliente_sbs isnull then '1' else '0' end as actualizar,
        b.cod_periodo
FROM SBS_DIM_CLIENTE A
LEFT JOIN sbs_fact_cliente B ON a.COD_CLIENTE_SBS = b.COD_CLIENTE_SBS
AND b.cod_periodo= 201601 -- 201601 @@p_periodo_actual@@ - MES DEL PROCESO - PARAMETRIZAR
      ) AS princ; 



DROP TABLE TP_SBS_DIM_CLIENTE_NOACTUALIZABLE;

CREATE TABLE TP_SBS_DIM_CLIENTE_NOACTUALIZABLE
( 
	COD_CLIENTE_SBS    NUMERIC   NOT NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_CLIENTE_PROP   NUMERIC   NULL ,
	TIP_DOCUMENTO_JUR  VARCHAR  NULL ,
	COD_DOCUMENTO_JUR  VARCHAR  NULL ,
	TIP_DOCUMENTO_NAT  VARCHAR  NULL ,
	COD_DOCUMENTO_NAT  VARCHAR  NULL ,
	TIP_PERSONA        VARCHAR  NULL ,
	COD_PERIODO_BANCARIZACION VARCHAR  NULL ,
	COD_PRODUCTO_BANCARIZACION VARCHAR  NULL ,
	COD_ENTIDAD_BANCARIZACION VARCHAR  NULL ,
	TIP_SITUACION_BANCARIZACION VARCHAR  NULL ,
	COD_PERIODO_COSECHA_PROP VARCHAR  NULL ,
	COD_PRODUCTO_COSECHA_PROP VARCHAR  NULL ,
	COD_PERIODO_ULT_PROP VARCHAR  NULL ,
	TIP_SITUACION_PROP VARCHAR  NULL ,
	NOM_PRIMER_NOMBRE  VARCHAR  NULL ,
	NOM_SEGUNDO_NOMBRE VARCHAR  NULL ,
	NOM_APE_PATERNO    VARCHAR  NULL ,
	NOM_APE_MATERNO    VARCHAR  NULL ,
	CNT_CPPDDP_3M      NUMERIC  NULL ,
	CNT_DDP_24M        NUMERIC  NULL ,
	CNT_NORMAL_12M     NUMERIC  NULL ,
	FLG_GARANTIA       VARCHAR  NULL ,
	FLG_SALDO_PMM_24M  NUMERIC  NULL ,
	MTO_SALDO_PP_MAX_24M NUMERIC  NULL ,
	MTO_LINEATC_MAX_24M NUMERIC  NULL ,
	MTO_SALDO_PMM_MAX_24M NUMERIC  NULL ,
	COD_PERIODO_SALDO_PP_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_LINEATC_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_PMM_MAX_24M VARCHAR  NULL ,
	COD_UBIGEO         VARCHAR(20)  NULL ,
	COD_SEGMENTO_PROP  VARCHAR  NULL ,
	TIP_MUNDO_CONSUMO  VARCHAR  NULL ,
	MTO_INGRESO_CLI    NUMERIC  NULL ,
	MTO_CUOTA_MES      NUMERIC  NULL ,
	COD_PERIODO_ULT    VARCHAR(100) NULL ,
	TIP_CLASIFICACION_ULTMES VARCHAR(100)  NULL ,
	TIP_MUNDO_PMM      VARCHAR(100) NULL ,
	TIP_MUNDO_HIP      VARCHAR(100) NULL,
    TIP_MUNDO_EMP      VARCHAR(100)  NULL
);

-- TEMPORAL PARA EL VASO DE AGUA ANTES DE INSERTAR EN LA DIM CLIENTE
DROP  TABLE  IF EXISTS TP_SBS_DIM_CLIENTE_TEMP;

CREATE TABLE TP_SBS_DIM_CLIENTE_TEMP
( 
	COD_CLIENTE_SBS    NUMERIC   NOT NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_CLIENTE_PROP   NUMERIC   NULL ,
	TIP_DOCUMENTO_JUR  VARCHAR  NULL ,
	COD_DOCUMENTO_JUR  VARCHAR  NULL ,
	TIP_DOCUMENTO_NAT  VARCHAR  NULL ,
	COD_DOCUMENTO_NAT  VARCHAR  NULL ,
	TIP_PERSONA        VARCHAR  NULL ,
	COD_PERIODO_BANCARIZACION VARCHAR  NULL ,
	COD_PRODUCTO_BANCARIZACION VARCHAR  NULL ,
	COD_ENTIDAD_BANCARIZACION VARCHAR  NULL ,
	TIP_SITUACION_BANCARIZACION VARCHAR  NULL ,
	COD_PERIODO_COSECHA_PROP VARCHAR  NULL ,
	COD_PRODUCTO_COSECHA_PROP VARCHAR  NULL ,
	COD_PERIODO_ULT_PROP VARCHAR  NULL ,
	TIP_SITUACION_PROP VARCHAR  NULL ,
	NOM_PRIMER_NOMBRE  VARCHAR  NULL ,
	NOM_SEGUNDO_NOMBRE VARCHAR  NULL ,
	NOM_APE_PATERNO    VARCHAR  NULL ,
	NOM_APE_MATERNO    VARCHAR  NULL ,
	CNT_CPPDDP_3M      NUMERIC  NULL ,
	CNT_DDP_24M        NUMERIC  NULL ,
	CNT_NORMAL_12M     NUMERIC  NULL ,
	FLG_GARANTIA       VARCHAR  NULL ,
	FLG_SALDO_PMM_24M  NUMERIC  NULL ,
	MTO_SALDO_PP_MAX_24M NUMERIC  NULL ,
	MTO_LINEATC_MAX_24M NUMERIC  NULL ,
	MTO_SALDO_PMM_MAX_24M NUMERIC  NULL ,
	COD_PERIODO_SALDO_PP_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_LINEATC_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_PMM_MAX_24M VARCHAR  NULL ,
	COD_UBIGEO         VARCHAR(20)  NULL ,
	COD_SEGMENTO_PROP  VARCHAR  NULL ,
	TIP_MUNDO_CONSUMO  VARCHAR  NULL ,
	MTO_INGRESO_CLI    NUMERIC  NULL ,
	MTO_CUOTA_MES      NUMERIC  NULL ,
	COD_PERIODO_ULT    VARCHAR(100) NULL ,
	TIP_CLASIFICACION_ULTMES VARCHAR(100)  NULL ,
	TIP_MUNDO_PMM      VARCHAR(100) NULL ,
	TIP_MUNDO_HIP      VARCHAR(100) NULL,
    TIP_MUNDO_EMP      VARCHAR(100)  NULL
);

-- insertamos los que no aparecen

INSERT INTO TP_SBS_DIM_CLIENTE_NOACTUALIZABLE
SELECT A.* -- o mencionar todos los campos 
FROM SBS_DIM_CLIENTE A, tp_flag_actualizar B
WHERE A.COD_CLIENTE_SBS = B.a_cod_cliente_sbs 
AND B.actualizar = '1';

-- los nuevos de sbs_fact_cliente
DROP TABLE TP_SBS_DIM_CLIENTE_ACTUALIZABLE;

CREATE TABLE TP_SBS_DIM_CLIENTE_ACTUALIZABLE
( 
	COD_CLIENTE_SBS    NUMERIC   NOT NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_CLIENTE_PROP   NUMERIC   NULL ,
	TIP_DOCUMENTO_JUR  VARCHAR  NULL ,
	COD_DOCUMENTO_JUR  VARCHAR  NULL ,
	TIP_DOCUMENTO_NAT  VARCHAR  NULL ,
	COD_DOCUMENTO_NAT  VARCHAR  NULL ,
	TIP_PERSONA        VARCHAR  NULL ,
	COD_PERIODO_BANCARIZACION VARCHAR  NULL ,
	COD_PRODUCTO_BANCARIZACION VARCHAR  NULL ,
	COD_ENTIDAD_BANCARIZACION VARCHAR  NULL ,
	TIP_SITUACION_BANCARIZACION VARCHAR  NULL ,
	COD_PERIODO_COSECHA_PROP VARCHAR  NULL ,
	COD_PRODUCTO_COSECHA_PROP VARCHAR  NULL ,
	COD_PERIODO_ULT_PROP VARCHAR  NULL ,
	TIP_SITUACION_PROP VARCHAR  NULL ,
	NOM_PRIMER_NOMBRE  VARCHAR  NULL ,
	NOM_SEGUNDO_NOMBRE VARCHAR  NULL ,
	NOM_APE_PATERNO    VARCHAR  NULL ,
	NOM_APE_MATERNO    VARCHAR  NULL ,
	CNT_CPPDDP_3M      NUMERIC  NULL ,
	CNT_DDP_24M        NUMERIC  NULL ,
	CNT_NORMAL_12M     NUMERIC  NULL ,
	FLG_GARANTIA       VARCHAR  NULL ,
	FLG_SALDO_PMM_24M  NUMERIC  NULL ,
	MTO_SALDO_PP_MAX_24M NUMERIC  NULL ,
	MTO_LINEATC_MAX_24M NUMERIC  NULL ,
	MTO_SALDO_PMM_MAX_24M NUMERIC  NULL ,
	COD_PERIODO_SALDO_PP_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_LINEATC_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_PMM_MAX_24M VARCHAR  NULL ,
	COD_UBIGEO         VARCHAR(20)  NULL ,
	COD_SEGMENTO_PROP  VARCHAR  NULL ,
	TIP_MUNDO_CONSUMO  VARCHAR  NULL ,
	MTO_INGRESO_CLI    NUMERIC  NULL ,
	MTO_CUOTA_MES      NUMERIC  NULL ,
	COD_PERIODO_ULT    VARCHAR(100) NULL ,
	TIP_CLASIFICACION_ULTMES VARCHAR(100)  NULL ,
	TIP_MUNDO_PMM      VARCHAR(100)  NULL ,
	TIP_MUNDO_HIP      VARCHAR(100)  NULL,
    TIP_MUNDO_EMP      VARCHAR(100)  NULL
);

-- PARA LOS CLIENTES NUEVOS
DROP TABLE TP_SBS_DIM_CLIENTE_NUEVOS;

CREATE TABLE TP_SBS_DIM_CLIENTE_NUEVOS
( 
	COD_CLIENTE_SBS    NUMERIC   NOT NULL ,
	TIP_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_DOCUMENTO_PRIN VARCHAR  NULL ,
	COD_CLIENTE_PROP   NUMERIC   NULL ,
	TIP_DOCUMENTO_JUR  VARCHAR  NULL ,
	COD_DOCUMENTO_JUR  VARCHAR  NULL ,
	TIP_DOCUMENTO_NAT  VARCHAR  NULL ,
	COD_DOCUMENTO_NAT  VARCHAR  NULL ,
	TIP_PERSONA        VARCHAR  NULL ,
	COD_PERIODO_BANCARIZACION VARCHAR  NULL ,
	COD_PRODUCTO_BANCARIZACION VARCHAR  NULL ,
	COD_ENTIDAD_BANCARIZACION VARCHAR  NULL ,
	TIP_SITUACION_BANCARIZACION VARCHAR  NULL ,
	COD_PERIODO_COSECHA_PROP VARCHAR  NULL ,
	COD_PRODUCTO_COSECHA_PROP VARCHAR  NULL ,
	COD_PERIODO_ULT_PROP VARCHAR  NULL ,
	TIP_SITUACION_PROP VARCHAR  NULL ,
	NOM_PRIMER_NOMBRE  VARCHAR  NULL ,
	NOM_SEGUNDO_NOMBRE VARCHAR  NULL ,
	NOM_APE_PATERNO    VARCHAR  NULL ,
	NOM_APE_MATERNO    VARCHAR  NULL ,
	CNT_CPPDDP_3M      NUMERIC  NULL ,
	CNT_DDP_24M        NUMERIC  NULL ,
	CNT_NORMAL_12M     NUMERIC  NULL ,
	FLG_GARANTIA       VARCHAR  NULL ,
	FLG_SALDO_PMM_24M  NUMERIC  NULL ,
	MTO_SALDO_PP_MAX_24M NUMERIC  NULL ,
	MTO_LINEATC_MAX_24M NUMERIC  NULL ,
	MTO_SALDO_PMM_MAX_24M NUMERIC  NULL ,
	COD_PERIODO_SALDO_PP_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_LINEATC_MAX_24M VARCHAR  NULL ,
	COD_PERIODO_PMM_MAX_24M VARCHAR  NULL ,
	COD_UBIGEO         VARCHAR(20)  NULL ,
	COD_SEGMENTO_PROP  VARCHAR  NULL ,
	TIP_MUNDO_CONSUMO  VARCHAR  NULL ,
	MTO_INGRESO_CLI    NUMERIC  NULL ,
	MTO_CUOTA_MES      NUMERIC  NULL ,
	COD_PERIODO_ULT    VARCHAR(100) NULL ,
	TIP_CLASIFICACION_ULTMES VARCHAR(100)  NULL ,
	TIP_MUNDO_PMM      VARCHAR(100)  NULL ,
	TIP_MUNDO_HIP      VARCHAR(100)  NULL,
    TIP_MUNDO_EMP      VARCHAR(100)  NULL
);

-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- desde aqui ya empiezo a calcular la dim_cliente si el codigo_sbs vino en el periodo actual 0
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- PASO 2 TEMPORAL PARA IDENTIFICAR COD_PERIODO_ULT

DROP TABLE TP_DIM_CLI_COD_PER_ULT;

create table TP_DIM_CLI_COD_PER_ULT
(
  cod_cliente_sbs   NUMERIC(18,2) not null,
  maxperiodo    NUMERIC(18,2),
  minperiodo    NUMERIC(18,2)
);


INSERT INTO  TP_DIM_CLI_COD_PER_ULT
SELECT A.COD_CLIENTE_SBS,MAX(A.COD_PERIODO) AS MAXPERIODO, MIN(A.COD_PERIODO) AS MINPERIODO
FROM SBS_FACT_SALDO A
JOIN sbs_ods_producto ON A.cod_subproducto = sbs_ods_producto.cod_subproducto 
AND sbs_ods_producto.Flg_producto in ('LINEA','SALDO')
GROUP BY A.COD_CLIENTE_SBS
ORDER BY A.COD_CLIENTE_SBS;

-- para pasar a otra sentencia espacio entre cada @@@  un espacio entre cada 
-- PASO 3 TEMPORAL PARA IDENTIFICAR EL CAMPO CNT_CPPDDP_3M ;

DROP TABLE TP_DIM_CLI_CNT_CPP_3M;


create table TP_DIM_CLI_CNT_CPP_3M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  CNT_CPPDDP_3M numeric(20)
);


insert into TP_DIM_CLI_CNT_CPP_3M
select cod_cliente_sbs, sum(cantidad) as CNT_CPPDDP_3M 
from 
(    select cod_cliente_sbs,  
    case when (por_saldo_deuda_tip1+
               por_saldo_deuda_tip2+
               por_saldo_deuda_tip3+
               por_saldo_deuda_tip4)>0 THEN 1 ELSE NULL END cantidad
    from sbs_ods_cliente 
    WHERE COD_PERIODO >=201510 -- @@p_num_3_meses@@ -- para periodo en duro anterior 201601
) tmp_sal_deud_tip
group by cod_cliente_sbs
ORDER by cod_cliente_sbs; 

-- PASO 4 TEMPORAL PARA IDENTIFICAR EL CAMPO CNT_DDP_24M 


DROP TABLE TP_DIM_CLI_CNT_DDP_24M;


create table TP_DIM_CLI_CNT_DDP_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  CNT_DDP_24M numeric(20)
);

insert into TP_DIM_CLI_CNT_DDP_24M
select cod_cliente_sbs, sum(cantidad) as CNT_DDP_24M 
from 
(    select cod_cliente_sbs,  
    case when (por_saldo_deuda_tip2+
               por_saldo_deuda_tip3+
               por_saldo_deuda_tip4)>0 THEN 1 ELSE NULL END cantidad
    from sbs_ods_cliente 
    WHERE COD_PERIODO >= 201401 -- @@p_num_24_meses@@ -- 201401 ---
) tmp_sal_deud_tip
group by cod_cliente_sbs
ORDER by cod_cliente_sbs;


-- PASO 5 TEMPORAL PARA IDENTIFICAR EL CAMPO CNT_NORMAL_12M 
DROP TABLE TP_DIM_CLI_CNT_NOR_12M;


create table TP_DIM_CLI_CNT_NOR_12M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  CNT_NOR_12M numeric(20)
);


insert into TP_DIM_CLI_CNT_NOR_12M
select cod_cliente_sbs, sum(cantidad) as CNT_NOR_12M 
from 
(    select cod_cliente_sbs,  
    case when por_saldo_deuda_tip0=100
         THEN 1 ELSE NULL END cantidad
    from sbs_ods_cliente 
    WHERE COD_PERIODO >= 201412-- @@p_num_12_meses@@ --201501
) tmp_sal_deud_tip
group by cod_cliente_sbs
ORDER by cod_cliente_sbs;

-- PASO 6 TEMPORAL PARA IDENTIFICAR FLG_GARANTIA
-- ----------------------------------------------------
DROP TABLE TP_DIM_CLI_FLG_GAR;


create table TP_DIM_CLI_FLG_GAR
(
  cod_cliente_sbs   NUMERIC(18,2) not null,
  maxperiodo    NUMERIC(18,2)
);


INSERT INTO  TP_DIM_CLI_FLG_GAR
SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS,MAX(SBS_FACT_SALDO.COD_PERIODO) AS MAXPERIODO
FROM SBS_FACT_SALDO 
JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
AND sbs_ods_producto.Flg_producto = 'GARANTIA' 
GROUP BY SBS_FACT_SALDO.COD_CLIENTE_SBS
ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;

-- PASO 7 TEMPORAL PARA IDENTIFICAR FLG_SALDO_PMM_24M
-- ----------------------------------------------------

DROP TABLE TP_DIM_CLI_FLG_SAL_PMM_24M;


create table TP_DIM_CLI_FLG_SAL_PMM_24M
(
  cod_cliente_sbs   NUMERIC(18,2) not null,
  CNT_FLG_SAL_PMM_24M numeric(20)  
);


INSERT INTO  TP_DIM_CLI_FLG_SAL_PMM_24M
SELECT COD_CLIENTE_SBS, SUM(CANTIDAD) AS FLG_SALDO_PMM_24M 
FROM
(
    SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS,1 AS CANTIDAD
    FROM SBS_FACT_SALDO 
    JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
    AND sbs_ods_producto.Flg_producto IN( 'MED','PEQ','MICRO') and  DES_TIPPRODUCTO='SALDO'
    WHERE COD_PERIODO >= 201401 -- @@p_num_24_meses@@ -- 201401 --- meses anteriores
    GROUP BY SBS_FACT_SALDO.COD_CLIENTE_SBS
) TMP_FLG_GAR
GROUP BY COD_CLIENTE_SBS
ORDER BY COD_CLIENTE_SBS;

-- PASO 8 TEMPORAL PARA IDENTIFICAR MTO_SALDO_PP_MAX_24M

DROP TABLE TP_DIM_CLI_MTO_SAL_PP_MAX_24M;


create table TP_DIM_CLI_MTO_SAL_PP_MAX_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  saldo         NUMERIC(18,2)
 );

-- 
 INSERT INTO TP_DIM_CLI_MTO_SAL_PP_MAX_24M
 SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS, MAX(SBS_FACT_SALDO.MTO_SALDO) AS MTO_SALDO
 FROM SBS_FACT_SALDO
 JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
 AND sbs_ods_producto.Flg_producto ='PRESTAMO' and  DES_TIPPRODUCTO='SALDO'
 WHERE SBS_FACT_SALDO.COD_PERIODO >=201401-- @@p_num_24_meses@@ -- 201401
 GROUP BY SBS_FACT_SALDO.COD_CLIENTE_SBS
 ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;

 -- PASO 9 TEMPORAL PARA IDENTIFICAR MTO_LINEATC_MAX_24M  

DROP TABLE TP_DIM_CLI_MTO_LIN_TC_MAX_24M;

create table TP_DIM_CLI_MTO_LIN_TC_MAX_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  saldo         NUMERIC(18,2)
 );


 INSERT INTO TP_DIM_CLI_MTO_LIN_TC_MAX_24M
 SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS, MAX(SBS_FACT_SALDO.MTO_SALDO) AS MTO_SALDO
 FROM SBS_FACT_SALDO
 JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
 AND sbs_ods_producto.Flg_producto ='TC' and  DES_TIPPRODUCTO='LINEA'
 WHERE SBS_FACT_SALDO.COD_PERIODO >= 201401--@@p_num_24_meses@@ --201401 ----@@p_num_24_meses@@
 GROUP BY SBS_FACT_SALDO.COD_CLIENTE_SBS
 ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;

 -- PASO 10 TEMPORAL PARA IDENTIFICAR MTO_SALDO_PMM_MAX_24M   

DROP TABLE TP_DIM_CLI_MTO_SAL_PMM_MAX_24M;

create table TP_DIM_CLI_MTO_SAL_PMM_MAX_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  saldo         NUMERIC(18,2)
 );


 INSERT INTO TP_DIM_CLI_MTO_SAL_PMM_MAX_24M
 SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS, MAX(SBS_FACT_SALDO.MTO_SALDO) AS MTO_SALDO
 FROM SBS_FACT_SALDO
 JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
 AND sbs_ods_producto.Flg_producto IN( 'MED','PEQ','MICRO') and  DES_TIPPRODUCTO='SALDO'
 WHERE SBS_FACT_SALDO.COD_PERIODO >= 201401 -- @@p_num_24_meses@@ --201401
 GROUP BY SBS_FACT_SALDO.COD_CLIENTE_SBS
 ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;
 

 -- PASO 11 TEMPORAL PARA IDENTIFICAR EL CAMPO COD_PERIODO_SALDO_PP_MAX_24M
 -- DEPENDE DE EL TEMPORAL (8) TP_DIM_CLI_MTO_SAL_PP_MAX_24M
 DROP TABLE TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M;

create table TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  PERIODO         NUMERIC(18,2)
 );

 
 INSERT INTO TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M 
 SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS,SBS_FACT_SALDO.COD_PERIODO FROM SBS_FACT_SALDO
 JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
 AND sbs_ods_producto.Flg_producto ='PRESTAMO' and  DES_TIPPRODUCTO='SALDO'
 JOIN TP_DIM_CLI_MTO_SAL_PP_MAX_24M 
 ON SBS_FACT_SALDO.COD_CLIENTE_SBS||'-'||SBS_FACT_SALDO.MTO_SALDO = TP_DIM_CLI_MTO_SAL_PP_MAX_24M.COD_CLIENTE_SBS||'-'||TP_DIM_CLI_MTO_SAL_PP_MAX_24M.SALDO
ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;


-- PASO 12 TEMPORAL PARA IDENTIFICAR EL CAMPO COD_PERIODO_LINEATC_MAX_24M 
-- DEPENDE DE EL TEMPORAL (9) TP_DIM_CLI_MTO_LIN_TC_MAX_24M
DROP TABLE TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M;


create table TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  PERIODO         NUMERIC(18,2)
 );

 
 INSERT INTO TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M 
 SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS,SBS_FACT_SALDO.COD_PERIODO FROM SBS_FACT_SALDO
 JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
 AND sbs_ods_producto.Flg_producto ='TC' and  DES_TIPPRODUCTO='LINEA'
 JOIN TP_DIM_CLI_MTO_LIN_TC_MAX_24M ON SBS_FACT_SALDO.COD_CLIENTE_SBS||'-'||SBS_FACT_SALDO.MTO_SALDO = TP_DIM_CLI_MTO_LIN_TC_MAX_24M.COD_CLIENTE_SBS||'-'||TP_DIM_CLI_MTO_LIN_TC_MAX_24M.SALDO
ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;

-- PASO 13 TEMPORAL PARA IDENTIFICAR EL CAMPO COD_PERIODO_PMM_MAX_24M  
-- DEPENDE DE EL TEMPORAL (10) TP_DIM_CLI_MTO_SAL_PMM_MAX_24M

 DROP TABLE TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M;

create table TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M
(
  cod_cliente_sbs NUMERIC(18,2) not null,
  PERIODO         NUMERIC(18,2)
 );

 
 INSERT INTO TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M 
 SELECT SBS_FACT_SALDO.COD_CLIENTE_SBS,SBS_FACT_SALDO.COD_PERIODO FROM SBS_FACT_SALDO
 JOIN sbs_ods_producto ON SBS_FACT_SALDO.cod_subproducto = sbs_ods_producto.cod_subproducto 
 AND sbs_ods_producto.Flg_producto ='TC' and  DES_TIPPRODUCTO='LINEA'
 JOIN TP_DIM_CLI_MTO_SAL_PMM_MAX_24M ON SBS_FACT_SALDO.COD_CLIENTE_SBS||'-'||SBS_FACT_SALDO.MTO_SALDO = TP_DIM_CLI_MTO_SAL_PMM_MAX_24M.COD_CLIENTE_SBS||'-'||TP_DIM_CLI_MTO_SAL_PMM_MAX_24M.SALDO
ORDER BY SBS_FACT_SALDO.COD_CLIENTE_SBS;
 
-- PRIMERO SE OBTIENE EL MIN COD_PERIODO SELECT * FROM TP_CLI_RCC_MES WHERE COD_CLIENTE_SBS = 61030786.00
-- ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡

DROP TABLE TP_CLI_RCC_MES;

CREATE TABLE TP_CLI_RCC_MES AS 
SELECT min(a.cod_periodo) AS COD_PERIODO_BANCARIZACION,
       a.COD_CLIENTE_SBS
FROM SBS_FACT_SALDO a inner  JOIN SBS_ODS_PRODUCTO b
ON  a.COD_SUBPRODUCTO = b.COD_SUBPRODUCTO
WHERE b.Flg_producto in ('LINEA','SALDO')
GROUP BY  a.cod_cliente_sbs;

-- ----------------------------------------------------------------------------------------------
-- 16.2 PASO PARA IDENTIFICAR LA COSECHA PERIODO Y PRODUCTO 
-- -----------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM;

create table TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM
(
  COD_CLIENTE_SBS NUMERIC(18,2) not null,
  COD_ENTIDAD     VARCHAR(10) not null,
  COD_SUBPRODUCTO VARCHAR(10) NOT NULL, 
  MINPERIODO      NUMERIC(18,2),
  MTO_SALDO       NUMERIC(18,2)
);

-- ******************* MODIFICACION *********************************************************
-- ------------------- PERIODO DE TP_COSECHA_CLI_ENT_PROD PARAMETRIZAR SELECT * FROM SBS_ODS_PRODUCTO
-- minimo periodo
drop table t_base_dim; -- SELECT * FROM TP_COSECHA_CLI_ENT_PROD WHERE COD_CLIENTE_SBS = 61030786.00

CREATE TABLE T_BASE_DIM AS
SELECT   COD_CLIENTE_SBS,  COD_ENTIDAD, MIN(MINPERIODO) AS MINPERIODO 
  FROM TP_COSECHA_CLI_ENT_PROD SALDO 
  INNER JOIN SBS_ODS_PRODUCTO PROD
  ON SALDO.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
   WHERE SALDO.MINPERIODO = 201601 -- @@p_periodo_actual@@
   AND 
   UPPER(PROD.FLG_PRODUCTO) in ('LINEA','SALDO')
   GROUP BY COD_CLIENTE_SBS,  COD_ENTIDAD; -- se debe poner periodo 

-- producto
drop table t_prod_dim; -- SELECT * FROM T_PROD_DIM WHERE COD_CLIENTE_SBS = 61030786.00

CREATE TABLE T_PROD_DIM AS
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, B.COD_SUBPRODUCTO ,
  A.MINPERIODO, MAX(B.MTO_SALDO) as MTO_SALDO
FROM T_BASE_dim AS A
	 INNER JOIN TP_COSECHA_CLI_ENT_PROD AS B
ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
AND A.COD_ENTIDAD = B.COD_ENTIDAD
AND A.MINPERIODO = B.MINPERIODO
	INNER JOIN SBS_ODS_PRODUCTO PROD
 ON B.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
WHERE UPPER(PROD.FLG_PRODUCTO) in ('LINEA','SALDO') -- AND B.
GROUP BY A.COD_CLIENTE_SBS,  A.COD_ENTIDAD, B.COD_SUBPRODUCTO, A.MINPERIODO;

-- SACAMOS EL MAXIMO 	
DROP TABLE T_MAXSAL_DIM; -- SALDO SELECT * FROM t_maxsal_DIM WHERE COD_CLIENTE_SBS = 61030786.00 

CREATE TABLE t_maxsal_DIM AS
SELECT A.COD_CLIENTE_SBS,A.MINPERIODO, MAX(A.MTO_SALDO) as MTO_SALDO
FROM T_PROD_DIM AS A
-- WHERE A.COD_CLIENTE_SBS = 61030786.00
 GROUP BY A.COD_CLIENTE_SBS, A.MINPERIODO;
 
-- SELECT * FROM T_MAXSAL_DIM_P WHERE COD_CLIENTE_SBS = 125736823.00 T_PROD_DIM
-- TABLA AGEGADA ----- CASI UNICA

DROP TABLE T_MAXSAL_DIM_P;

CREATE TABLE T_MAXSAL_DIM_P AS
SELECT A.*
   FROM T_PROD_DIM A INNER JOIN  T_MAXSAL_DIM B 
   ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS AND A.MINPERIODO = B.MINPERIODO AND A.MTO_SALDO = B.MTO_SALDO;
   -- WHERE A.COD_CLIENTE_SBS = 61030786.00 

-- ********************************************************************
-- INSERTAMOS NUEVAS TABLAS PARA LOS DUPLICADOS 125736823.00
-- -----------------------------------------------------------------
-- SELECT * FROM T_MAXSAL_DIM_1 WHERE COD_CLIENTE_SBS = 125736823 
-- SELECT * FROM T_MAXSAL_DIM_1  -- UBICAMOS Y SEPARAMOS LOS UNICOS
DROP TABLE T_MAXSAL_DIM_1;

CREATE TABLE T_MAXSAL_DIM_1 AS
SELECT * FROM T_MAXSAL_DIM_P
WHERE COD_CLIENTE_SBS IN (
                           SELECT A.COD_CLIENTE_SBS -- , COUNT(A.COD_CLIENTE_SBS) UNICOS
                           FROM T_MAXSAL_DIM_P A
                           GROUP BY A.COD_CLIENTE_SBS 
                           HAVING COUNT(A.COD_CLIENTE_SBS) =1);
      
-- UBICAMOS Y SEPARAMOS LOS DUPLICADOS SELECT * FROM T_MAXSAL_DIM_P
DROP TABLE T_MAXSAL_D1;

CREATE TABLE T_MAXSAL_D1 AS 
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO
       ,CASE WHEN A.COD_ENTIDAD = '237' THEN 1
              WHEN A.COD_ENTIDAD = '1'   THEN 2
              WHEN A.COD_ENTIDAD = '101' THEN 3
              WHEN A.COD_ENTIDAD = '102' THEN 4
              WHEN A.COD_ENTIDAD = '103' THEN 5
              WHEN A.COD_ENTIDAD = '104' THEN 6
              WHEN A.COD_ENTIDAD = '105' THEN 7
              WHEN A.COD_ENTIDAD = '106' THEN 8
              WHEN A.COD_ENTIDAD = '107' THEN 9
              ELSE 10 END AS PRI_ENTIDAD   -- SI HAY VARIOS 10
FROM T_MAXSAL_DIM_P A 
WHERE A.COD_CLIENTE_SBS IN (SELECT A.COD_CLIENTE_SBS -- COUNT(A.COD_CLIENTE_SBS) -- DUPLICADOS
                           FROM T_MAXSAL_DIM_P A
                           GROUP BY A.COD_CLIENTE_SBS 
                           HAVING COUNT(A.COD_CLIENTE_SBS) >1);
                           -- SELECT * FROM T_MAXSAL_D1 WHERE COD_CLIENTE_SBS = 125736823
-- CREAMOS LA TABLA DIFERENTES A MIN_ENTIDAD 10 125736823.00

DROP TABLE T_MAXSAL_D2; 

   CREATE TABLE  T_MAXSAL_D2 AS                       
   SELECT A.COD_CLIENTE_SBS, A.MINPERIODO, MIN(A.PRI_ENTIDAD) AS MIN_ENTIDAD
   FROM T_MAXSAL_D1 A
   WHERE PRI_ENTIDAD <> 10
   GROUP BY  A.COD_CLIENTE_SBS, A.MINPERIODO; 
   
-- SELECT * FROM T_MAXSAL_D10 WHERE COD_CLIENTE_SBS=66129578
DROP TABLE T_MAXSAL_D10;

   CREATE TABLE  T_MAXSAL_D10 AS                       
   SELECT A.COD_CLIENTE_SBS,A.MINPERIODO, MIN(A.COD_ENTIDAD) AS MIN_ENTIDAD
   FROM T_MAXSAL_D1 A
   WHERE PRI_ENTIDAD =10 AND A.COD_CLIENTE_SBS NOT IN (SELECT COD_CLIENTE_SBS FROM T_MAXSAL_D2)
   GROUP BY  A.COD_CLIENTE_SBS,A.MINPERIODO; 
  
-- HACEMOS UN UNION DE LAS TABLAS
DROP TABLE T_MAXSAL_DIM_2;

CREATE TABLE T_MAXSAL_DIM_2 AS
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD,A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO
      FROM T_MAXSAL_D1 A
INNER JOIN T_MAXSAL_D2 B ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS AND A.PRI_ENTIDAD = B.MIN_ENTIDAD AND A.MINPERIODO = B.MINPERIODO
-- WHERE A.COD_CLIENTE_SBS = 66129578
UNION 
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD,A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO
       FROM T_MAXSAL_D1 A
INNER JOIN T_MAXSAL_D10 B ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS AND A.COD_ENTIDAD = B.MIN_ENTIDAD AND A.MINPERIODO = B.MINPERIODO
;
-- WHERE A.COD_CLIENTE_SBS = 66129578     
-- SELECT * FROM  T_MAXSAL_D1 WHERE COD_CLIENTE_SBS= 66129578 
-- CODIGOS QUE MAS SE REPITEN 1, 101, 102, -- 107
-- UNIMOS LAS DOS TABLAS SELECT * FROM T_MAXSAL_DIM_2 WHERE COD_CLIENTE_SBS= 66129578.00 

DROP TABLE NEW_T_MAXSAL; 

CREATE TABLE NEW_T_MAXSAL AS
SELECT * FROM T_MAXSAL_DIM_1
UNION 
SELECT * FROM T_MAXSAL_DIM_2;
 
-- 

drop table T_BASE_1_DIM;

CREATE TABLE T_BASE_1_DIM AS           
SELECT ROW_NUMBER() OVER() AS NRO,
		A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO
  FROM T_PROD_DIM AS A INNER JOIN NEW_T_MAXSAL AS B -- CAMBIAR LA TABLANEW_T_MAXSAL
 ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
	AND A.COD_ENTIDAD = B.COD_ENTIDAD
	AND A.MINPERIODO = B.MINPERIODO
	AND A.MTO_SALDO = B.MTO_SALDO;
-- SELECT * FROM T_BASE_1_DIM WHERE COD_CLIENTE_SBS=61030786

drop table T_BASE_2_DIM ;

CREATE TABLE T_BASE_2_DIM AS
 SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, A.MTO_SALDO, MAX(A.NRO) AS MAXNRO 
 FROM T_BASE_1_DIM AS A
 GROUP BY A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, A.MTO_SALDO;
-- 
TRUNCATE TABLE TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM; -- TABLA registros UNICos !!!!!!!! OK

INSERT INTO TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM
 SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO 
 FROM 
 T_BASE_1_DIM AS A INNER JOIN T_BASE_2_DIM AS Y
 ON A.NRO = Y.MAXNRO
;


-- ----------------------------------------------------------------------------------------------
-- 16.3 PASO PARA IDENTIFICAR LA COSECHA PERIODO Y PRODUCTO PROP
-- ----------- -- SELECT * FROM TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP WHERE cod_cliente_sbs = 71098044.00

DROP TABLE IF EXISTS TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP;

create table TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP
(
  COD_CLIENTE_SBS NUMERIC(18,2) not null,
  COD_ENTIDAD     VARCHAR(10) not null,
  COD_SUBPRODUCTO VARCHAR(10) NOT NULL, 
  MINPERIODO      NUMERIC(18,2),
  MTO_SALDO       NUMERIC(18,2)
);

drop table t_base_prop; -- SELECT * FROM t_base_prop WHERE cod_cliente_sbs = 71098044.00

CREATE TABLE T_BASE_PROP AS
SELECT   COD_CLIENTE_SBS,  COD_ENTIDAD, MIN(MINPERIODO) AS MINPERIODO 
  FROM TP_COSECHA_CLI_ENT_PROD SALDO 
  INNER JOIN SBS_ODS_PRODUCTO PROD
  ON SALDO.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
   WHERE
   COD_ENTIDAD='237' --PARAMETRIZAR CODIGO DE ENTIDAD
   AND UPPER(PROD.FLG_PRODUCTO)='SALDO'
GROUP BY COD_CLIENTE_SBS,  COD_ENTIDAD;

drop table t_prod_prop; -- SELECT * FROM T_MAXSAL_PROP WHERE cod_cliente_sbs = 71098044.00

CREATE TABLE T_PROD_PROP AS
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, B.COD_SUBPRODUCTO ,
  A.MINPERIODO, MAX(B.MTO_SALDO) as MTO_SALDO
FROM T_BASE_PROP AS A
	 INNER JOIN TP_COSECHA_CLI_ENT_PROD AS B
ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
AND A.COD_ENTIDAD = B.COD_ENTIDAD
AND A.MINPERIODO = B.MINPERIODO
	INNER JOIN SBS_ODS_PRODUCTO PROD
 ON B.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
WHERE UPPER(PROD.FLG_PRODUCTO)='SALDO'
GROUP BY A.COD_CLIENTE_SBS,  A.COD_ENTIDAD, B.COD_SUBPRODUCTO, A.MINPERIODO;
		
drop table t_maxsal_prop; -- SELECT * FROM T_MAXSAL_PROP WHERE cod_cliente_sbs = 71098044.00

CREATE TABLE T_MAXSAL_PROP AS         
SELECT 
  A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, MAX(A.MTO_SALDO) as MTO_SALDO
FROM T_PROD_PROP AS A
 GROUP BY A.COD_CLIENTE_SBS,  A.COD_ENTIDAD, A.MINPERIODO;
 
drop table T_BASE_1_PROP;  -- SELECT * FROM T_BASE_1_PROP WHERE cod_cliente_sbs = 71098044.00

CREATE TABLE T_BASE_1_PROP AS           
SELECT ROW_NUMBER() OVER() AS NRO,
		A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO
  FROM T_PROD_PROP AS A INNER JOIN T_MAXSAL_PROP AS B
 ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
	AND A.COD_ENTIDAD = B.COD_ENTIDAD
	AND A.MINPERIODO = B.MINPERIODO
	AND A.MTO_SALDO = B.MTO_SALDO;

drop table T_BASE_2_PROP ; -- SELECT * FROM T_BASE_2_PROP WHERE cod_cliente_sbs = 71098044.00

CREATE TABLE T_BASE_2_PROP AS
 SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, A.MTO_SALDO, MAX(A.NRO) AS MAXNRO 
 FROM T_BASE_1_PROP AS A
 GROUP BY A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, A.MTO_SALDO;

-- SELECT * FROM TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP WHERE cod_cliente_sbs = 71098044.00
INSERT INTO TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP
 SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO 
 FROM T_BASE_1_PROP AS A INNER JOIN T_BASE_2_PROP AS Y
 ON A.NRO = Y.MAXNRO
;
-- paso para identificar tip_situacion_prop
drop table TP_DIM_CLI_TIP_SITUACION_PROP;

create table TP_DIM_CLI_TIP_SITUACION_PROP
(
  COD_CLIENTE_SBS NUMERIC(18,2) not null,
  MTO_ULT_PERIODO NUMERIC(18,2),
  MTO_PEN_PERIODO NUMERIC(18,2)
);

-- select * from TP_DIM_CLI_TIP_SITUACION_PROP WHERE cod_cliente_sbs = 71098044.00
INSERT INTO TP_DIM_CLI_TIP_SITUACION_PROP 
select cod_cliente_sbs, sum(ult_periodo) ult_periodo, sum(pen_periodo) pen_periodo from
(
    select cod_cliente_sbs,  
    case when cod_periodo='201601' then saldo else 0 end ult_periodo, -- parametrizar @@p_periodo_actual@@
    case when cod_periodo<>'201601' then saldo else 0 end pen_periodo  -- parametrizar
    from (
        select cod_cliente_sbs, cod_periodo, cod_entidad, sum(mto_saldo) as saldo
        from sbs_fact_saldo 
        where cod_periodo >= 201601 -- parametrizar
        and cod_entidad = '237' --parametrizar
        group by cod_cliente_sbs, cod_periodo, cod_entidad
        order by cod_cliente_sbs
    ) as tabla_temp
 ) as tabla_temp_per
 group by cod_cliente_sbs
ORDER BY COD_CLIENTE_SBS;


-- ************************************************************************************
-- ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ CORRECCION ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡

INSERT INTO TP_SBS_DIM_CLIENTE_NUEVOS 
SELECT
 
   F_CLIENTE.COD_CLIENTE_SBS,
    F_CLIENTE.TIP_DOCUMENTO_PRIN, 
    F_CLIENTE.COD_DOCUMENTO_PRIN,
    NULL as COD_CLIENTE_PROP, --COD_CLIENTE_PROP,
    CLIENTE.TIP_DOCUMENTO_TRIB, --TIP_DOCUMENTO_JUR
    CLIENTE.COD_RUC, --COD_DOCUMENTO_JUR
    CLIENTE.TIP_DOCUMENTO_IDENT, --TIP_DOCUMENTO_NAT
    CLIENTE.COD_DNI, --COD_DOCUMENTO_NAT
    CLIENTE.TIP_PERSONA, --TIP_PERSONA
    TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.MINPERIODO,-- COD_PERIODO_BANCARIZACION TOMAR DE LA TABLE TEMPORAL TP_CLI_RCC_MES cambiar 
    TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.COD_SUBPRODUCTO,-- COD_PRODUCTO_BANCARIZACION TOMAR DE LA TABLA TEMPORAL TP_CLI_RCC_MES
    TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.COD_ENTIDAD,--COD_ENTIDAD_BANCARIZACION TOMAR DE LA TABLA TEMPORTAL TP_CLI_RCC_MES_ENT 
    F_CLIENTE.TIP_SIT_BANCARIZACION, -- TIP_SITUACION_BANCARIZACION
    TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP.MINPERIODO ,--COD_PERIODO_COSECHA PROP 
    TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP.COD_SUBPRODUCTO, --COD_PRODUCTO_COSECHA_PROP FALTA CALCULAR
    F_CLIENTE.COD_PERIODO AS  COD_PERIODO_ULT_PROP, --
    CASE WHEN TP_DIM_CLI_TIP_SITUACION_PROP.MTO_ULT_PERIODO>0 THEN 'CLIENTE'
         WHEN TP_DIM_CLI_TIP_SITUACION_PROP.MTO_PEN_PERIODO>0 THEN 'EX - CLIENTE'
         ELSE 'NO CLIENTE' END,--TIP_SITUACION_PROP
    CLIENTE.NOM_PRIMER_NOMBRE, --NOM_PRIMER_NOMBRE
    CLIENTE.NOM_SEGUNDO_NOMBRE, --NOM_SEGUNDO_NOMBRE
    CLIENTE.NOM_RAZON_SOCIAL,-- NOM_APE_PATERNO
    CLIENTE.NOM_APE_MATERNO, --NOM_APE_MATERNO
    CASE WHEN TP_DIM_CLI_CNT_CPP_3M.CNT_CPPDDP_3M =3 THEN 1 ELSE NULL END, --CNT_CPPDDP_3M
    CASE WHEN TP_DIM_CLI_CNT_DDP_24M.CNT_DDP_24M = 24 THEN 1 ELSE NULL END, --CNT_DDP_24M
    CASE WHEN TP_DIM_CLI_CNT_NOR_12M.CNT_NOR_12M = 12 THEN 1 ELSE NULL END, -- CNT_NOR_12M
    CASE WHEN TP_DIM_CLI_FLG_GAR.MAXPERIODO = 201601 THEN 1 ELSE NULL END, -- FLG_GARANTIA- 201601 PARAMETRIZAR 
    CASE WHEN TP_DIM_CLI_FLG_SAL_PMM_24M.CNT_FLG_SAL_PMM_24M =24 THEN 1 ELSE NULL END, --FLG_SALDO_PMM_24M 
    TP_DIM_CLI_MTO_SAL_PP_MAX_24M.SALDO , --MTO_SALDO_PP_MAX_24M 
    TP_DIM_CLI_MTO_LIN_TC_MAX_24M.SALDO, --MTO_LINEATC_MAX_24M 
    TP_DIM_CLI_MTO_SAL_PMM_MAX_24M.SALDO, --MTO_SALDO_PMM_MAX_24M 
    TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M.PERIODO, --COD_PERIODO_SALDO_PP_MAX_24M 
    TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M.PERIODO, --COD_PERIODO_LINEATC_MAX_24M 
    TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M.PERIODO, --COD_PERIODO_PMM_MAX_24M
    F_CLIENTE.COD_UBIGEO, --COD_UBIGEO
    F_CLIENTE.COD_SEGMENTO_PROP, --COD_SEGMENTO
    F_CLIENTE.TIP_MUNDO_CONSUMO , --TIP_MUNDO_CONSUMO 
    F_CLIENTE.MTO_INGRESO, --MTO_INGRESO
    F_CLIENTE.MTO_CUOTA_MES, --MTO_CUOTA_MES
    TP_DIM_CLI_COD_PER_ULT.MAXPERIODO, --COD_PERIODO_ULT
    F_CLIENTE.TIP_CLASIFICACION , --TIP_CLASIFICACION_ULTMES
    F_CLIENTE.TIP_MUNDO_PMM, --TIP_MUNDO_PMM 
    F_CLIENTE.TIP_MUNDO_HIP , --TIP_MUNDO_HIP 
    F_CLIENTE.TIP_MUNDO_EMP  --TIP_MUNDO_EMP

FROM sbs_fact_cliente F_CLIENTE
 INNER JOIN SBS_ODS_CLIENTE CLIENTE ON F_CLIENTE.COD_CLIENTE_SBS = CLIENTE.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_ULT ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_ULT.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_CNT_CPP_3M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_CNT_CPP_3M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_CNT_DDP_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_CNT_DDP_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_CNT_NOR_12M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_CNT_NOR_12M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_FLG_GAR ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_FLG_GAR.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_FLG_SAL_PMM_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_FLG_SAL_PMM_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_MTO_SAL_PP_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_MTO_SAL_PP_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_MTO_LIN_TC_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_MTO_LIN_TC_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_MTO_SAL_PMM_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_MTO_SAL_PMM_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM ON F_CLIENTE.COD_CLIENTE_SBS = TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.COD_CLIENTE_SBS 
 LEFT JOIN TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP ON F_CLIENTE.COD_CLIENTE_SBS = TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_TIP_SITUACION_PROP ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_TIP_SITUACION_PROP.COD_CLIENTE_SBS
 
WHERE F_CLIENTE.COD_CLIENTE_SBS NOT IN (SELECT COD_CLIENTE_SBS FROM SBS_DIM_CLIENTE) -- DIM CLIENTE
 AND F_CLIENTE.COD_PERIODO = 201601  -- PARAMETRIZAR
 AND CLIENTE.COD_PERIODO =   201601; -- PARAMETRIZAR

-- ACTUALIZABLES  

INSERT INTO TP_SBS_DIM_CLIENTE_ACTUALIZABLE 
SELECT
 
   F_CLIENTE.COD_CLIENTE_SBS,
    F_CLIENTE.TIP_DOCUMENTO_PRIN, 
    F_CLIENTE.COD_DOCUMENTO_PRIN,
    NULL as COD_CLIENTE_PROP, --COD_CLIENTE_PROP,
    CLIENTE.TIP_DOCUMENTO_TRIB, --TIP_DOCUMENTO_JUR
    CLIENTE.COD_RUC, --COD_DOCUMENTO_JUR
    CLIENTE.TIP_DOCUMENTO_IDENT, --TIP_DOCUMENTO_NAT
    CLIENTE.COD_DNI, --COD_DOCUMENTO_NAT
    CLIENTE.TIP_PERSONA, --TIP_PERSONA
    TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.MINPERIODO,-- COD_PERIODO_BANCARIZACION TOMAR DE LA TABLE TEMPORAL TP_CLI_RCC_MES cambiar 
    TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.COD_SUBPRODUCTO,-- COD_PRODUCTO_BANCARIZACION TOMAR DE LA TABLA TEMPORAL TP_CLI_RCC_MES
    TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.COD_ENTIDAD,--COD_ENTIDAD_BANCARIZACION TOMAR DE LA TABLA TEMPORTAL TP_CLI_RCC_MES_ENT 
    F_CLIENTE.TIP_SIT_BANCARIZACION, -- TIP_SITUACION_BANCARIZACION
    TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP.MINPERIODO ,--COD_PERIODO_COSECHA PROP 
    TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP.COD_SUBPRODUCTO, --COD_PRODUCTO_COSECHA_PROP FALTA CALCULAR
    F_CLIENTE.COD_PERIODO AS  COD_PERIODO_ULT_PROP, --
    CASE WHEN TP_DIM_CLI_TIP_SITUACION_PROP.MTO_ULT_PERIODO>0 THEN 'CLIENTE'
         WHEN TP_DIM_CLI_TIP_SITUACION_PROP.MTO_PEN_PERIODO>0 THEN 'EX - CLIENTE'
         ELSE 'NO CLIENTE' END,--TIP_SITUACION_PROP
    CLIENTE.NOM_PRIMER_NOMBRE, --NOM_PRIMER_NOMBRE
    CLIENTE.NOM_SEGUNDO_NOMBRE, --NOM_SEGUNDO_NOMBRE
    CLIENTE.NOM_RAZON_SOCIAL,-- NOM_APE_PATERNO
    CLIENTE.NOM_APE_MATERNO, --NOM_APE_MATERNO
    CASE WHEN TP_DIM_CLI_CNT_CPP_3M.CNT_CPPDDP_3M =3 THEN 1 ELSE NULL END, --CNT_CPPDDP_3M
    CASE WHEN TP_DIM_CLI_CNT_DDP_24M.CNT_DDP_24M = 24 THEN 1 ELSE NULL END, --CNT_DDP_24M
    CASE WHEN TP_DIM_CLI_CNT_NOR_12M.CNT_NOR_12M = 12 THEN 1 ELSE NULL END, -- CNT_NOR_12M
    CASE WHEN TP_DIM_CLI_FLG_GAR.MAXPERIODO = 201601 THEN 1 ELSE NULL END, -- FLG_GARANTIA- 201601 PARAMETRIZAR 
    CASE WHEN TP_DIM_CLI_FLG_SAL_PMM_24M.CNT_FLG_SAL_PMM_24M =24 THEN 1 ELSE NULL END, --FLG_SALDO_PMM_24M 
    TP_DIM_CLI_MTO_SAL_PP_MAX_24M.SALDO , --MTO_SALDO_PP_MAX_24M 
    TP_DIM_CLI_MTO_LIN_TC_MAX_24M.SALDO, --MTO_LINEATC_MAX_24M 
    TP_DIM_CLI_MTO_SAL_PMM_MAX_24M.SALDO, --MTO_SALDO_PMM_MAX_24M 
    TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M.PERIODO, --COD_PERIODO_SALDO_PP_MAX_24M 
    TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M.PERIODO, --COD_PERIODO_LINEATC_MAX_24M 
    TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M.PERIODO, --COD_PERIODO_PMM_MAX_24M
    F_CLIENTE.COD_UBIGEO, --COD_UBIGEO
    F_CLIENTE.COD_SEGMENTO_PROP, --COD_SEGMENTO
    F_CLIENTE.TIP_MUNDO_CONSUMO , --TIP_MUNDO_CONSUMO 
    F_CLIENTE.MTO_INGRESO, --MTO_INGRESO
    F_CLIENTE.MTO_CUOTA_MES, --MTO_CUOTA_MES
    TP_DIM_CLI_COD_PER_ULT.MAXPERIODO, --COD_PERIODO_ULT
    F_CLIENTE.TIP_CLASIFICACION , --TIP_CLASIFICACION_ULTMES
    F_CLIENTE.TIP_MUNDO_PMM, --TIP_MUNDO_PMM 
    F_CLIENTE.TIP_MUNDO_HIP , --TIP_MUNDO_HIP 
    F_CLIENTE.TIP_MUNDO_EMP  --TIP_MUNDO_EMP

FROM sbs_fact_cliente F_CLIENTE
 INNER JOIN SBS_ODS_CLIENTE CLIENTE ON F_CLIENTE.COD_CLIENTE_SBS = CLIENTE.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_ULT ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_ULT.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_CNT_CPP_3M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_CNT_CPP_3M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_CNT_DDP_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_CNT_DDP_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_CNT_NOR_12M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_CNT_NOR_12M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_FLG_GAR ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_FLG_GAR.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_FLG_SAL_PMM_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_FLG_SAL_PMM_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_MTO_SAL_PP_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_MTO_SAL_PP_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_MTO_LIN_TC_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_MTO_LIN_TC_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_MTO_SAL_PMM_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_MTO_SAL_PMM_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_SAL_PP_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_LIN_TC_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_COD_PER_SAL_PMM_MAX_24M.COD_CLIENTE_SBS
 LEFT JOIN TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM ON F_CLIENTE.COD_CLIENTE_SBS = TP_COSECHA_CLI_ENT_PROD_COSECHA_DIM.COD_CLIENTE_SBS 
 LEFT JOIN TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP ON F_CLIENTE.COD_CLIENTE_SBS = TP_COSECHA_CLI_ENT_PROD_COSECHA_PROP.COD_CLIENTE_SBS
 LEFT JOIN TP_DIM_CLI_TIP_SITUACION_PROP ON F_CLIENTE.COD_CLIENTE_SBS = TP_DIM_CLI_TIP_SITUACION_PROP.COD_CLIENTE_SBS
 
WHERE 
 F_CLIENTE.COD_CLIENTE_SBS IN (SELECT A_COD_CLIENTE_SBS FROM tp_flag_actualizar WHERE actualizar = '0') AND
 F_CLIENTE.COD_PERIODO = 201601  -- PARAMETRIZAR
 AND CLIENTE.COD_PERIODO =   201601; -- PARAMETRIZAR;



--DELETE CAMBIA POR VASO DE AGUA
--DELETE FROM SBS_DIM_CLIENTE
--            WHERE COD_CLIENTE_SBS IN (SELECT A_COD_CLIENTE_SBS FROM tp_flag_actualizar WHERE actualizar = '0') ;

--VASO DE AGUA
INSERT INTO TP_SBS_DIM_CLIENTE_TEMP
SELECT * FROM tp_flag_actualizar WHERE actualizar <> '0';
TRUNCATE TABLE SBS_DIM_CLIENTE;

INSERT INTO SBS_DIM_CLIENTE
SELECT * FROM TP_SBS_DIM_CLIENTE_TEMP;


INSERT INTO SBS_DIM_CLIENTE
SELECT * -- O PONER TODOS LOS CAMPOS
FROM TP_SBS_DIM_CLIENTE_NUEVOS
UNION 
SELECT * -- O PONER TODOS LOS CAMPOS
FROM TP_SBS_DIM_CLIENTE_ACTUALIZABLE; 
