DROP TABLE IF EXISTS TP_COSECHA_CLI_ENT_PROD_COSECHA;

@@@

create table TP_COSECHA_CLI_ENT_PROD_COSECHA
(
  COD_CLIENTE_SBS NUMERIC(18,2) not null,
  COD_ENTIDAD     VARCHAR(10) not null,
  COD_SUBPRODUCTO VARCHAR(10) NOT NULL, 
  MINPERIODO      NUMERIC(18,2),
  MTO_SALDO       NUMERIC(18,2)
);

@@@

CREATE TABLE T_BASE AS
SELECT   COD_CLIENTE_SBS,  COD_ENTIDAD, MIN(MINPERIODO) AS MINPERIODO 
  FROM TP_COSECHA_CLI_ENT_PROD SALDO 
  INNER JOIN SBS_ODS_PRODUCTO PROD
  ON SALDO.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
   WHERE UPPER(PROD.FLG_PRODUCTO)='SALDO'
GROUP BY COD_CLIENTE_SBS,  COD_ENTIDAD;

@@@

CREATE TABLE T_PROD AS
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, B.COD_SUBPRODUCTO ,
  A.MINPERIODO, MAX(B.MTO_SALDO) as MTO_SALDO
FROM T_BASE AS A
	 INNER JOIN TP_COSECHA_CLI_ENT_PROD AS B
ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
AND A.COD_ENTIDAD = B.COD_ENTIDAD
AND A.MINPERIODO = B.MINPERIODO
	INNER JOIN SBS_ODS_PRODUCTO PROD
 ON B.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
WHERE UPPER(PROD.FLG_PRODUCTO)='SALDO'
GROUP BY A.COD_CLIENTE_SBS,  A.COD_ENTIDAD, B.COD_SUBPRODUCTO, A.MINPERIODO;
		
@@@

CREATE TABLE T_MAXSAL AS         
SELECT 
  A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, MAX(A.MTO_SALDO) as MTO_SALDO
FROM T_PROD AS A
 GROUP BY A.COD_CLIENTE_SBS,  A.COD_ENTIDAD, A.MINPERIODO;
 
@@@

CREATE TABLE T_BASE_1 AS           
SELECT ROW_NUMBER() OVER() AS NRO,
		A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO
  FROM T_PROD AS A INNER JOIN T_MAXSAL AS B
 ON A.COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
	AND A.COD_ENTIDAD = B.COD_ENTIDAD
	AND A.MINPERIODO = B.MINPERIODO
	AND A.MTO_SALDO = B.MTO_SALDO;

@@@

CREATE TABLE T_BASE_2 AS
 SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, A.MTO_SALDO, MAX(A.NRO) AS MAXNRO 
 FROM T_BASE_1 AS A
 GROUP BY A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.MINPERIODO, A.MTO_SALDO;

 @@@

INSERT INTO TP_COSECHA_CLI_ENT_PROD_COSECHA
 SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, A.COD_SUBPRODUCTO, A.MINPERIODO, A.MTO_SALDO 
 FROM T_BASE_1 AS A INNER JOIN T_BASE_2 AS Y
 ON A.NRO = Y.MAXNRO
;

@@@
------------------------------------------------------
--FACT CLIENTE ENTIDAD
------------------------------------------------------


INSERT INTO SBS_FACT_CLIENTE_ENTIDAD
(
COD_PERIODO,
COD_CLIENTE_SBS,
TIP_DOCUMENTO_PRIN,
COD_DOCUMENTO_PRIN,
COD_ENTIDAD,
TIP_CLASIFICACION,
COD_PERIODO_COSECHA,
COD_SUBPRODUCTO_COSECHA,
MTO_SALDO,
MTO_SALDO_INDIRECTO,
MTO_SALDO_CONSUMO,
MTO_SALDO_CONSUMO_TC,
MTO_SALDO_CONSUMO_LD,
MTO_SALDO_CONSUMO_VEH,
MTO_SALDO_CONSUMO_TC_DEF,
MTO_SALDO_LINEATC,
MTO_SALDO_MICRO,
MTO_SALDO_PEQ,
MTO_SALDO_MED,
MTO_SALDO_LINEA_PMM,
MTO_SALDO_HIP ,
MTO_SALDO_HIP_MIV,
MTO_SALDO_EMP,
MTO_SALDO_LINEAEMP,
MTO_SALDO_REFINANCIADO,
MTO_SALDO_CASTIGO,
MTO_SALDO_JUDICIAL,
MTO_CUOTA_MES,
COD_UBIGEO
)
SELECT
SALDO.COD_PERIODO       AS COD_PERIODO,
SALDO.COD_CLIENTE_SBS   AS COD_CLIENTE_SBS,
CLI.TIP_DOCUMENTO_PRIN  AS TIP_DOCUMENTO_PRIN,
CLI.COD_DOCUMENTO_PRIN  AS COD_DOCUMENTO_PRIN,
SALDO.COD_ENTIDAD       AS COD_ENTIDAD,
SALDO.TIP_CLASIFICACION AS TIP_CLASIFICACION,
COSECHA.MINPERIODO      AS COD_PERIODO_COSECHA,
COSECHA.COD_SUBPRODUCTO AS COD_SUBPRODUCTO_COSECHA,
SUM( CASE WHEN UPPER(PROD.FLG_PRODUCTO) = 'SALDO'  THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO,
SUM( CASE WHEN UPPER(PROD.FLG_PRODUCTO) <> 'SALDO'  THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_INDIRECTO,
SUM( CASE WHEN UPPER(PROD.COD_FAMPRODUCTO) = 'C' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_CONSUMO,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'TCRD'     AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_CONSUMO_TC,
SUM( CASE WHEN UPPER(SALDO.COD_SUBPRODUCTO) = 'PTMLDI'     AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_CONSUMO_LD,
SUM( CASE WHEN UPPER(SALDO.COD_SUBPRODUCTO) = 'PTMVEH'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_CONSUMO_VEH,
SUM( CASE WHEN UPPER(SALDO.COD_SUBPRODUCTO) = 'DEFETC'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_CONSUMO_TC_DEF,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'TCRD'     AND UPPER(PROD.FLG_PRODUCTO)='LINEA' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_LINEATC,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'CMIC'  AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_MICRO,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'CPEQ'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_PEQ,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'CMED'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_MED,
SUM( CASE WHEN UPPER(PROD.COD_FAMPRODUCTO) = 'P' AND TIP_PRODUCTO='LINEA' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_LINEA_PMM,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'HIPO'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_HIP,
SUM( CASE WHEN UPPER(SALDO.COD_SUBPRODUCTO) = 'HIPMIV'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_HIP_MIV,
SUM( CASE WHEN UPPER(PROD.COD_FAMPRODUCTO) = 'E'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_EMP,
SUM( CASE WHEN UPPER(PROD.COD_FAMPRODUCTO) = 'E'    AND UPPER(PROD.FLG_PRODUCTO)='LINEA' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_LINEAEMP,
SUM( CASE WHEN UPPER(SALDO.COD_SITCREDITO) = '4' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_REFINANCIADO,
SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'CSTG'   AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_CASTIGO,
SUM( CASE WHEN UPPER(SALDO.COD_SITCREDITO) = '6'    AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) AS MTO_SALDO_JUDICIAL,
0.05*SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'TCRD' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) + 
0.05*0.2*(SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'TCRD' AND UPPER(PROD.FLG_PRODUCTO)='LINEA' THEN SALDO.MTO_SALDO ELSE 0 END) - 
          SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'TCRD' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END)) + 
0.04*(SUM( CASE WHEN UPPER(PROD.COD_FAMPRODUCTO) = 'C' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) - 
      SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'TCRD' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END)) + 
0.04*(SUM( CASE WHEN UPPER(PROD.COD_FAMPRODUCTO) = 'P' AND UPPER(PROD.TIP_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END)) + 
0.01*SUM( CASE WHEN UPPER(PROD.COD_PRODUCTO) = 'HIPO' AND UPPER(PROD.FLG_PRODUCTO)='SALDO' THEN SALDO.MTO_SALDO ELSE 0 END) MTO_CUOTA_MES,
CLI.COD_UBIGEO AS COD_UBIGEO
FROM SBS_FACT_SALDO SALDO 
    LEFT OUTER JOIN SBS_DIM_CLIENTE CLI   ON SALDO.COD_CLIENTE_SBS = CLI.COD_CLIENTE_SBS 
    LEFT OUTER JOIN SBS_ODS_PRODUCTO PROD ON SALDO.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
    INNER JOIN TP_COSECHA_CLI_ENT_PROD_COSECHA COSECHA
ON SALDO.COD_CLIENTE_SBS = COSECHA.COD_CLIENTE_SBS AND SALDO.COD_ENTIDAD = COSECHA.COD_ENTIDAD AND SALDO.COD_SUBPRODUCTO = COSECHA.COD_SUBPRODUCTO
WHERE SALDO.COD_PERIODO =  @@p_cod_periodo@@ --PARAMETRO MES
GROUP BY 
SALDO.COD_PERIODO,
SALDO.COD_CLIENTE_SBS,
CLI.TIP_DOCUMENTO_PRIN,
CLI.COD_DOCUMENTO_PRIN,
SALDO.COD_ENTIDAD,
SALDO.TIP_CLASIFICACION,
COSECHA.MINPERIODO,
COSECHA.COD_SUBPRODUCTO,
CLI.COD_UBIGEO;

@@@

DROP TABLE T_BASE;
@@@
DROP TABLE T_BASE_1;
@@@
DROP TABLE T_BASE_2;
@@@
DROP TABLE T_MAXSAL;
@@@
DROP TABLE T_PROD;