-- ELIMINA EL ULTIMO PERIODO DE TODAS LAS TABLAS FACT

CREATE TABLE T_FACT_SALDO AS
SELECT * FROM SBS_FACT_SALDO
WHERE COD_PERIODO < @@p_cod_periodo@@;
@@@
TRUNCATE TABLE SBS_FACT_SALDO;
@@@
DROP INDEX IDX_FACT_SALDO_PK;
@@@
INSERT INTO SBS_FACT_SALDO
SELECT * FROM T_FACT_SALDO;
@@@
CREATE UNIQUE INDEX IDX_FACT_SALDO_PK 
ON SBS_FACT_SALDO (COD_PERIODO ,COD_CLIENTE_SBS ,COD_CUENTA, NUM_CONDICION_DIAS,TIP_CREDITO ,COD_ENTIDAD ,COD_SUBPRODUCTO );
@@@
DROP TABLE T_FACT_SALDO;
@@@

CREATE TABLE T_FACT_CLIENTE_ENTIDAD_PROD AS
SELECT * FROM SBS_FACT_CLIENTE_ENTIDAD_PROD
WHERE COD_PERIODO < @@p_cod_periodo@@;
@@@
TRUNCATE TABLE SBS_FACT_CLIENTE_ENTIDAD_PROD;
@@@
DROP INDEX IDX_FACT_CLIENTE_ENTIDAD_PROD_PK;
@@@
INSERT INTO SBS_FACT_CLIENTE_ENTIDAD_PROD
SELECT * FROM T_FACT_CLIENTE_ENTIDAD_PROD;
@@@
CREATE UNIQUE INDEX IDX_FACT_CLIENTE_ENTIDAD_PROD_PK 
ON SBS_FACT_CLIENTE_ENTIDAD_PROD (COD_PERIODO ,COD_CLIENTE_SBS ,COD_ENTIDAD ,COD_SUBPRODUCTO );
@@@
DROP TABLE T_FACT_CLIENTE_ENTIDAD_PROD;
@@@

CREATE TABLE T_FACT_CLIENTE_ENTIDAD AS
SELECT * FROM SBS_FACT_CLIENTE_ENTIDAD
WHERE COD_PERIODO < @@p_cod_periodo@@;
@@@
TRUNCATE TABLE SBS_FACT_CLIENTE_ENTIDAD;
@@@
DROP INDEX IDX_FACT_CLIENTE_ENTIDAD_PK;
@@@
INSERT INTO SBS_FACT_CLIENTE_ENTIDAD
SELECT * FROM T_FACT_CLIENTE_ENTIDAD;
@@@
CREATE UNIQUE INDEX IDX_FACT_CLIENTE_ENTIDAD_PK 
ON SBS_FACT_CLIENTE_ENTIDAD (COD_PERIODO ,COD_CLIENTE_SBS ,COD_ENTIDAD );
@@@
DROP TABLE T_FACT_CLIENTE_ENTIDAD;
@@@

CREATE TABLE T_FACT_CLIENTE AS
SELECT * FROM SBS_FACT_CLIENTE
WHERE COD_PERIODO < @@p_cod_periodo@@;
@@@
TRUNCATE TABLE SBS_FACT_CLIENTE;
@@@
DROP INDEX IDX_FACT_CLIENTE_PK;
@@@
INSERT INTO SBS_FACT_CLIENTE
SELECT * FROM T_FACT_CLIENTE;
@@@
CREATE UNIQUE INDEX IDX_FACT_CLIENTE_PK 
ON SBS_FACT_CLIENTE (COD_PERIODO ,COD_CLIENTE_SBS);
@@@
DROP TABLE T_FACT_CLIENTE;
@@@

