TRUNCATE SBS_ODS_CLIENTE;

@@@

INSERT INTO SBS_ODS_CLIENTE
SELECT
to_number(to_char(TO_DATE(fec_reporte, 'YYYYMMDD'),'yyyymm'),'999999') as COD_PERIODO,
COD_CLIENTE_SBS,
FEC_REPORTE,
TIP_DOCUMENTO_TRIB,
CASE WHEN CHAR_LENGTH(COD_RUC) < 11 AND CHAR_LENGTH(COD_RUC) > 0 then  LPAD(COD_RUC, 11 ,'0') ELSE SUBSTR(COD_RUC,0,12) END 
AS COD_RUC,
TIP_DOCUMENTO_IDENT,
CASE TIP_DOCUMENTO_IDENT 
WHEN '1' THEN 
CASE WHEN COD_DNI IS NOT NULL THEN LPAD(COD_DNI, 8 ,'0') END 
WHEN '2' THEN 
CASE WHEN COD_DNI IS NOT NULL THEN LPAD(COD_DNI, 9 ,'0') END 
WHEN '7' THEN 
CASE WHEN COD_DNI IS NOT NULL THEN LPAD(COD_DNI, 11 ,'0') END 
END
AS COD_DNI, -- puede ser otro ademas de DNI??
TIP_PERSONA,
TIP_EMPRESA,
CNT_EMPRESA,
POR_SALDO_DEUDA_TIP0,
POR_SALDO_DEUDA_TIP1,
POR_SALDO_DEUDA_TIP2,
POR_SALDO_DEUDA_TIP3,
POR_SALDO_DEUDA_TIP4,
NOM_RAZON_SOCIAL,
NOM_APE_MATERNO,
NOM_APE_CASADA,
NOM_PRIMER_NOMBRE,
NOM_SEGUNDO_NOMBRE
FROM SBS_STG_CLIENTE;
