TRUNCATE SBS_ODS_SALDO;

@@@

INSERT INTO SBS_ODS_SALDO 
SELECT
to_number(to_char(TO_DATE(fec_reporte, 'YYYYMMDD'),'yyyymm'),'999999') as COD_PERIODO,
COD_CLIENTE_SBS,
COD_ENTIDAD,
TIP_CREDITO,
COD_CUENTA,
NUM_CONDICION_DIAS,
SUM(MTO_SALDO)/100 AS MTO_SALDO,
TIP_CLASIFICACION,
FEC_REPORTE
FROM SBS_STG_SALDO
GROUP BY 
to_number(to_char(TO_DATE(fec_reporte, 'YYYYMMDD'),'yyyymm'),'999999'),
COD_CLIENTE_SBS,
COD_ENTIDAD,
TIP_CREDITO,
COD_CUENTA,
NUM_CONDICION_DIAS,
TIP_CLASIFICACION,
FEC_REPORTE;