INSERT INTO SBS_FACT_SALDO
(
COD_CLIENTE_SBS,
COD_ENTIDAD,
TIP_CREDITO,
COD_CUENTA,
NUM_CONDICION_DIAS,
MTO_SALDO,
TIP_CLASIFICACION,
COD_SITCREDITO,
COD_SUBPRODUCTO,
COD_PERIODO,
COD_UBIGEO
)
SELECT
SBS_ODS_SALDO.COD_CLIENTE_SBS,
SBS_ODS_SALDO.COD_ENTIDAD,
SBS_ODS_SALDO.TIP_CREDITO,
SBS_ODS_SALDO.COD_CUENTA,
SBS_ODS_SALDO.NUM_CONDICION_DIAS,
SBS_ODS_SALDO.MTO_SALDO,
SBS_ODS_SALDO.TIP_CLASIFICACION,
SUBSTR(SBS_ODS_SALDO.COD_CUENTA,4,1),
CASE WHEN SBS_ODS_REL_PRODUCTO.COD_SUBPRODUCTO IS NULL THEN '.' ELSE SBS_ODS_REL_PRODUCTO.COD_SUBPRODUCTO END AS COD_SUBPRODUCTO,
SBS_ODS_SALDO.COD_PERIODO,
191100 --PARAMETRIZAR EL MES UBIGEO DEL CLIENTE
FROM SBS_ODS_SALDO LEFT OUTER JOIN SBS_DIM_CLIENTE
    ON SBS_ODS_SALDO.COD_CLIENTE_SBS = SBS_DIM_CLIENTE.COD_CLIENTE_SBS
      LEFT OUTER JOIN SBS_ODS_REL_PRODUCTO
    ON SBS_ODS_SALDO.Cod_Cuenta = SBS_ODS_REL_PRODUCTO.Cod_Cuenta
      AND SBS_ODS_SALDO.TIP_CREDITO = SBS_ODS_REL_PRODUCTO.Tip_Credito
      AND SBS_ODS_SALDO.COD_PERIODO = SBS_ODS_REL_PRODUCTO.COD_PERIODO
      WHERE SBS_ODS_SALDO.COD_PERIODO =  @@p_cod_periodo@@ --MES A PROCESAR PARAMETRIZAR
;
