
 DROP TABLE IF EXISTS TP_COSECHA_CLI_ENT_PROD_MES;
 
@@@ 

 --IDENTIFICAMOS LOS CLIENTES NUEVOS QUE DEBEN UNIRSE A LA FACT TODOS LOS NUEVOS
 CREATE TABLE TP_COSECHA_CLI_ENT_PROD_MES AS
 SELECT   A.COD_CLIENTE_SBS,  A.COD_ENTIDAD, A.COD_SUBPRODUCTO, (A.COD_PERIODO) AS MINPERIODO 
  FROM SBS_FACT_SALDO A
    INNER JOIN  TP_COSECHA_CLI_ENT_PROD B
  ON   A.COD_CLIENTE_SBS  = B.COD_CLIENTE_SBS
  AND  A.COD_ENTIDAD      = B.COD_ENTIDAD
  AND  A.COD_SUBPRODUCTO  = B.COD_SUBPRODUCTO
  WHERE A.COD_PERIODO = @@p_cod_periodo@@ --MES DEL PROCESO
    AND B.COD_CLIENTE_SBS IS NULL AND B.cod_entidad  IS NULL AND B.COD_SUBPRODUCTO IS NULL;

 @@@
 --INSERT NUEVOS CLIENTES A LA TABLA
INSERT INTO  TP_COSECHA_CLI_ENT_PROD
SELECT A.COD_CLIENTE_SBS, A.COD_ENTIDAD, B.COD_SUBPRODUCTO, 
       B.MINPERIODO AS MINPERIODO, SUM(A.MTO_SALDO) AS MTO_SALDO
  FROM SBS_FACT_SALDO A
INNER JOIN TP_COSECHA_CLI_ENT_PROD_MES B
     ON A.COD_CLIENTE_SBS   = B.COD_CLIENTE_SBS
    AND A.COD_ENTIDAD       = B.COD_ENTIDAD
    AND A.COD_SUBPRODUCTO   = B.COD_SUBPRODUCTO 
  WHERE A.COD_PERIODO          = @@p_cod_periodo@@ --MES DEL PROCEO
 GROUP BY
 A.COD_CLIENTE_SBS, 
 A.COD_ENTIDAD, 
 B.COD_SUBPRODUCTO,
 B.MINPERIODO;

 @@@
------------------------------------------------------
--FACT CLIENTE ENTIDAD PRODUCTO
------------------------------------------------------

INSERT INTO SBS_FACT_CLIENTE_ENTIDAD_PROD
(
cod_periodo, 
cod_cliente_sbs, 
cod_documento_prin, 
cod_entidad, 
tip_clasificacion, 
cod_subproducto, 
mto_saldo, 
cod_periodo_cosecha, 
tip_estado_producto, 
tip_documento_prin, 
cod_ubigeo
)
SELECT
SALDO.COD_PERIODO AS COD_PERIODO,
SALDO.COD_CLIENTE_SBS AS COD_CLIENTE_SBS,
CLI.COD_DOCUMENTO_PRIN AS COD_DOCUMENTO_PRIN,
SALDO.COD_ENTIDAD AS COD_ENTIDAD,
SALDO.TIP_CLASIFICACION AS TIP_CLASIFICACION,
SALDO.COD_SUBPRODUCTO AS COD_SUBPRODUCTO,
SUM(SALDO.MTO_SALDO) AS MTO_SALDO,
MINPERIODO AS COD_PERIODO_COSECHA,	
CASE WHEN COSE.MINPERIODO = SALDO.COD_PERIODO THEN 'ALTA'
ELSE 'RECURRENTE' END TIP_ESTADO_PRODUCTO, 
CLI.TIP_DOCUMENTO_PRIN AS TIP_DOCUMENTO_PRINC,
CLI.COD_UBIGEO
FROM SBS_FACT_SALDO SALDO 
    LEFT OUTER JOIN SBS_DIM_CLIENTE CLI   ON SALDO.COD_CLIENTE_SBS = CLI.COD_CLIENTE_SBS 
    LEFT OUTER JOIN SBS_ODS_PRODUCTO PROD ON SALDO.COD_SUBPRODUCTO = PROD.COD_SUBPRODUCTO
    LEFT OUTER JOIN TP_COSECHA_CLI_ENT_PROD COSE ON SALDO.COD_CLIENTE_SBS = COSE.COD_CLIENTE_SBS 
    AND SALDO.COD_ENTIDAD = COSE.COD_ENTIDAD  AND SALDO.COD_SUBPRODUCTO =COSE.COD_SUBPRODUCTO
    WHERE SALDO.COD_PERIODO =  @@p_cod_periodo@@ --MES A PROCESAR
GROUP BY 
SALDO.COD_PERIODO,
SALDO.COD_CLIENTE_SBS,
CLI.COD_DOCUMENTO_PRIN,
SALDO.COD_ENTIDAD,
SALDO.TIP_CLASIFICACION,
SALDO.COD_SUBPRODUCTO,
MINPERIODO,
CASE WHEN COSE.MINPERIODO = SALDO.COD_PERIODO THEN 'ALTA'
ELSE 'RECURRENTE' END, 
CLI.TIP_DOCUMENTO_PRIN,
CLI.COD_UBIGEO;

@@@
------------------------------------------------------
--ACTUALIZACION DEL MES ANTERIOR
------------------------------------------------------

DROP TABLE IF EXISTS TP_CLIENTE_SBS_BAJA_ANT;

@@@

CREATE TABLE TP_CLIENTE_SBS_BAJA_ANT AS 
WITH MESES    AS (SELECT COD_PERIODO, COUNT(1)  FROM SBS_FACT_CLIENTE_ENTIDAD_PROD  GROUP BY COD_PERIODO),
     ORDEN    AS (SELECT DENSE_RANK() OVER (ORDER BY COD_PERIODO DESC) AS NRO, COD_PERIODO FROM MESES),
     MES_ANT  AS (SELECT COD_PERIODO FROM ORDEN WHERE nro = 2),
     MES_ACT  AS (SELECT COD_PERIODO FROM ORDEN WHERE nro = 1)
SELECT ANT.COD_CLIENTE_SBS, ANT.COD_ENTIDAD, ANT.COD_SUBPRODUCTO, (SELECT COD_PERIODO FROM MES_ACT) AS COD_PERIODO FROM 
( 
  SELECT COD_CLIENTE_SBS, COD_ENTIDAD, COD_SUBPRODUCTO FROM SBS_FACT_CLIENTE_ENTIDAD_PROD 
  WHERE COD_PERIODO     = (SELECT COD_PERIODO FROM MES_ANT) AND TIP_ESTADO_PRODUCTO = 'ALTA'
)ANT
LEFT OUTER JOIN 
(
  SELECT COD_CLIENTE_SBS, COD_ENTIDAD, COD_SUBPRODUCTO FROM SBS_FACT_CLIENTE_ENTIDAD_PROD
  WHERE   COD_PERIODO     = (SELECT COD_PERIODO FROM MES_ACT) AND TIP_ESTADO_PRODUCTO = 'ALTA'
) ACT
ON   ANT.COD_CLIENTE_SBS = ACT.COD_CLIENTE_SBS
AND   ANT.COD_ENTIDAD     = ACT.COD_ENTIDAD
AND   ANT.COD_SUBPRODUCTO    = ACT.COD_SUBPRODUCTO
AND   (ACT.COD_CLIENTE_SBS IS NULL  AND ACT.COD_ENTIDAD IS NULL AND ACT.COD_SUBPRODUCTO IS NULL) 
;
@@@

UPDATE SBS_FACT_CLIENTE_ENTIDAD_PROD AS A
SET TIP_ESTADO_PRODUCTO = 'BAJA'
WHERE 
A.COD_PERIODO = @@p_cod_periodo@@ --MES A PROCESAR
AND
EXISTS (SELECT 1 FROM TP_CLIENTE_SBS_BAJA_ANT B
            WHERE COD_CLIENTE_SBS = B.COD_CLIENTE_SBS
              AND COD_ENTIDAD     = B.COD_ENTIDAD
              AND COD_SUBPRODUCTO    = B.COD_SUBPRODUCTO
              AND COD_PERIODO     = B.COD_PERIODO
			LIMIT 1			  );

@@@
--DROP TABLE IF EXISTS TP_COSECHA_CLI_ENT_PROD;
DROP TABLE IF EXISTS TP_MES_ANTERIOR;
@@@
DROP TABLE IF EXISTS TP_CLIENTE_SBS_BAJA_ANT;
